--Switch to the master system database so we can drop AttendanceDB safely
USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'AttendanceDB')
BEGIN
    ALTER DATABASE AttendanceDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE AttendanceDB;
END
GO


CREATE DATABASE AttendanceDB;
GO
USE AttendanceDB;
GO 

CREATE TABLE PROGRAMS (
    ProgramID INT IDENTITY(1,1) PRIMARY KEY,
    ProgramName VARCHAR(100) NOT NULL
);

CREATE TABLE ADVISERS (
    AdviserID VARCHAR(50) PRIMARY KEY, 
    AdviserName VARCHAR(150) NOT NULL
);

CREATE TABLE EVENTS (
    EventID INT IDENTITY(1,1) PRIMARY KEY,
    EventName VARCHAR(150) NOT NULL
);

CREATE TABLE SECTIONS (
    SectionID INT IDENTITY(1,1) PRIMARY KEY,
    SectionName VARCHAR(50) NOT NULL, 
    ProgramID INT NOT NULL,
    CONSTRAINT FK_Sections_Programs FOREIGN KEY (ProgramID) REFERENCES PROGRAMS(ProgramID)
);

CREATE TABLE STUDENTS (
    StudentID VARCHAR(50) PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    SectionID INT NOT NULL,
    CONSTRAINT FK_Students_Sections FOREIGN KEY (SectionID) REFERENCES SECTIONS(SectionID)
);

CREATE TABLE EVENT_PROGRAMS (
    EventID INT NOT NULL,
    ProgramID INT NOT NULL,
    PRIMARY KEY (EventID, ProgramID), 
    CONSTRAINT FK_EvProg_Events FOREIGN KEY (EventID) REFERENCES EVENTS(EventID) ON DELETE CASCADE,
    CONSTRAINT FK_EvProg_Programs FOREIGN KEY (ProgramID) REFERENCES PROGRAMS(ProgramID)
);

CREATE TABLE EVENT_SECTIONS (
    EventID INT NOT NULL,
    SectionID INT NOT NULL,
    PRIMARY KEY (EventID, SectionID),
    CONSTRAINT FK_EvSec_Events FOREIGN KEY (EventID) REFERENCES EVENTS(EventID) ON DELETE CASCADE,
    CONSTRAINT FK_EvSec_Sections FOREIGN KEY (SectionID) REFERENCES SECTIONS(SectionID)
);

CREATE TABLE EVENT_ADVISERS (
    EventID INT NOT NULL,
    AdviserID VARCHAR(50) NOT NULL,
    PRIMARY KEY (EventID, AdviserID),
    CONSTRAINT FK_EvAdv_Events FOREIGN KEY (EventID) REFERENCES EVENTS(EventID) ON DELETE CASCADE,
    CONSTRAINT FK_EvAdv_Advisers FOREIGN KEY (AdviserID) REFERENCES ADVISERS(AdviserID)
);

CREATE TABLE ATTENDANCE_LOGS (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    StudentID VARCHAR(50) NOT NULL,
    EventID INT NOT NULL,
    ProgramID INT NOT NULL,
    SectionID INT NOT NULL,
    AdviserID VARCHAR(50) NOT NULL,
    AttendanceStatus VARCHAR(20) NOT NULL, 
    LogTimestamp DATETIME DEFAULT GETDATE(), 
    
    CONSTRAINT FK_Logs_Students FOREIGN KEY (StudentID) REFERENCES STUDENTS(StudentID),
    CONSTRAINT FK_Logs_Events FOREIGN KEY (EventID) REFERENCES EVENTS(EventID),
    CONSTRAINT FK_Logs_Programs FOREIGN KEY (ProgramID) REFERENCES PROGRAMS(ProgramID),
    CONSTRAINT FK_Logs_Sections FOREIGN KEY (SectionID) REFERENCES SECTIONS(SectionID),
    CONSTRAINT FK_Logs_Advisers FOREIGN KEY (AdviserID) REFERENCES ADVISERS(AdviserID)
);